spring:
  application:
    name: apigateway

  cloud:
    gateway:
      routes:
        -id: goods
        uri: lb://GOODS-SERVICE
        predicates:
          - Path=/goods-service/**
          - Method=GET, POST, PUT, DELETE
        filters:
          - RemoveRequestHeader=Cookie
          - RewritePath=/goods-service/(?<segment>.*), /$\{segment}

server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httpexchanges, busrefresh, info, metrics, prometheus