spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/kch0527/shop-msa-config
          default-label: main

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"